CREATE TABLE autor (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(160) NOT NULL,
    email VARCHAR(254) NOT NULL,
    descricao VARCHAR(400) NOT NULL,
    data_cadastro DATETIME NOT NULL,
    PRIMARY KEY (id));